twitter/accounts/urls.py
from django.urls import path

from . import views

# set the application namespace
# https://docs.djangoproject.com/en/2.0/intro/tutorial03/
app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
]

twitter/tweet/urls.py
from django.urls import path
from . import views

app_name = 'tweet'
urlpatterns = [
    path('post/lists',                     views.PostView.as_view(),    name ='post_list'),
    path('<str:subject_name>/<int:times>', views.PostCreate.as_view(),  name ='class_post_new'),
    path('', views.RedirectFirstSubject.as_view(),      name ='class_default_new'),
]

twitter/twitter/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',          include('tweet.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('emoji/',    include('emoji.urls')),
]

twitter/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


import sys
sys.path.append("../")
from tweet.models import Subject



class ClassUser(AbstractUser):
    subject = models.ManyToManyField(Subject, choices=((s.pk, s) for s in Subject.objects.all()))

twitter/tweet/models.py
from django.db import models
from django.utils import timezone
from django.utils.deconstruct import deconstructible


class Post(models.Model):
    user           = models.ForeignKey('accounts.ClassUser', on_delete=models.CASCADE)
    text           = models.TextField()
    created_date   = models.DateTimeField(default=timezone.now)
    times          = models.IntegerField(default=1)
    subject        = models.ForeignKey('Subject', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.text


class FixPost(models.Model):
    title          = models.TextField()
    text           = models.TextField()
    created_date   = models.DateTimeField(default=timezone.now)
    times          = models.IntegerField(default=1)
    subject        = models.ForeignKey('Subject', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.title


@deconstructible
class Subject(models.Model):
    title    = models.CharField(max_length=100, null=True)
    times    = models.IntegerField()


    def __str__(self):
        return self.title

twitter/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import ClassUser

import sys
sys.path.append("../")
from tweet.models import Subject


class SignUpForm(UserCreationForm):
    subject = forms.ModelMultipleChoiceField(
        queryset=Subject.objects.all(),
        label='subject',
        help_text='参加している授業を選択して下さい',
        widget=forms.CheckboxSelectMultiple())

    class Meta:
        model = ClassUser
        fields = ('username', 'subject')

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.save()
        user.subject.set(self.data.getlist('subject'))
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

twitter/tweet/forms.py
from django import forms

from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('user','text')

twitter/accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic
from .forms import SignUpForm


class SignUpView(generic.CreateView):
    form_class = SignUpForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

twitter/tweet/views.py
from django.views import generic
from django.utils import timezone
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Post, Subject


class RedirectFirstSubject(LoginRequiredMixin, generic.base.RedirectView):
    permanent = False
    query_string = True

    def get_redirect_url(self, *args, **kwargs):
        first_subject = self.request.user.subject.all()[0]
        self.url = '/' + first_subject.title + '/' + str(first_subject.times)
        return super().get_redirect_url(*args, **kwargs)


class PostView(LoginRequiredMixin, generic.ListView):
    context_object_name = 'posts'

    def get_queryset(self):
        return Post.objects.all()


class PostCreate(LoginRequiredMixin, generic.CreateView):
    model = Post
    fields = ['text']

    def form_valid(self, form):
        form.instance.user        = self.request.user
        form.instance.create_date = timezone.now
        form.instance.times       = self._get_subject_times()
        form.instance.subject     = self._get_context_subject()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        kwargs['user_object_list'] = self._get_post_filter_times().filter(user_id__gt=1)
        kwargs['root_object_list'] = self._get_post_filter_times().filter(user_id=1)
        kwargs['fix_post_list']    = self._get_fix_post_filter_times().all()
        kwargs['path']             = self.request.path
        kwargs['nav_title_times']  = self._get_subject_title() + '第' + str(self._get_subject_times()) + '回'
        return super(PostCreate, self).get_context_data(**kwargs)
    
    def get_success_url(self):
        return self.request.path

    def _get_post_filter_times(self):
        """postをsubject_timesでfilter"""
        return self._get_context_subject().post_set.filter(times=self._get_subject_times())

    def _get_fix_post_filter_times(self):
        """fixpostをsubject_timesでfilter"""
        return self._get_context_subject().fixpost_set.filter(times=self._get_subject_times())

    def _get_context_subject(self):
        return Subject.objects.filter(title=self._get_subject_title())[0]

    def _get_subject_title(self):
        """現在開いている教科のtitle取得 /math/2 => ['', 'math', '2'] => math """
        return self.request.path.split('/')[1]

    def _get_subject_times(self):
        """現在開いている教科の回数取得 /math/2 => ['', 'math', '2'] => 2 """
        return self.request.path.split('/')[2]

twitter/accounts/templates/accounts/signup.html
{% extends 'tweet/base.html' %}

{% load static %}
{% load widget_tweaks %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'accounts/style.css' %}" />

<form method="post" novalidate>
  {% csrf_token %}
  {% include 'registration/bootstrap_form.html' %}
  <button type="submit" class="btn btn-success">Post</button>
</form>

{% endblock %}

twitter/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <title>{% if request.path != '/' %}{% block title %}{% endblock %} | {% endif %}Blog App with Auth | Django2 Tutorial</title>
</head>
<body>
<div class="container">
    <header>
        <nav>
            <ul>
                {% if user.is_authenticated %}
                <li><a href="{% url 'logout' %}" class="logout">Logout</a></li>
                {% else %}
                <li><a href="{% url 'accounts:signup' %}" class="signup">Sign up</a></li>
                <li><a href="{% url 'login' %}" class="login">Login</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>
    <div class="content">
        {% block content %}{% endblock %}
    </div>
</div>
</body>
</html>

twitter/tweet/templates/tweet/base.html
{% load staticfiles %}
{% load range %}
<html>
    <head>
        <title>tweet</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
    </head>

    <body>
        <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
            <div class="navbar-brand">{{nav_title_times}}</div>
            {% if request.user.is_anonymous %}
                <div class="navbar-brand">授業管理システム</div>
            {% endif %}
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="collapsibleNavbar">
                <ul class="navbar-nav mr-auto">
                    {% for s in request.user.subject.all %}
                    <li class="dropdown nav-link">
                        <a class="dropdown-toggle" data-toggle="dropdown" > {{s}}
                            <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            {% for i in s.times|range %}
                                <li><a href="/{{s}}/{{i}}">第{{i}}回目</a></li>
                            {% endfor %}
                        </ul>
                    </li>
                    {% endfor %}
                </ul>
                <ul class="navbar-nav">
                    {% if request.user.is_anonymous %}
                    <li class="nav-item"> <a class="nav-link" href="/accounts/signup">Signup</a> </li>
                    <li class="nav-item"> <a class="nav-link" href="/accounts/login">LogIn</a>   </li>
                    <div class="navbar-brand"> ログインして下さい</div>

                    {% else %}
                        <div class="navbar-brand">{{request.user}}</div>
                    <li class="nav-item"> <a class="nav-link" href="/accounts/logout">Logout</a> </li>
                    {% endif %}
                </ul>
            </div>
        </nav>

        <div class="container" style="margin-top:30px">
            <div class="row">
                {% block content %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

twitter/tweet/templates/tweet/post_form.html
{% extends 'tweet/base.html' %}
{% load bootstrap4 %}
{% load static %}
{% load widget_tweaks %}

{% block content %}
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="{% static 'tweet/css/emoji.css' %}" />

  <script src="{% static 'tweet/js/config.js' %}">           </script>
  <script src="{% static 'tweet/js/util.js' %}">             </script>
  <script src="{% static 'tweet/js/jquery.emojiarea.js' %}"> </script>
  <script src="{% static 'tweet/js/emoji-picker.js' %}">     </script>

<div class="col-sm-8">
    <h1>New post</h1>

    <form method="POST" class="post-form" action="{{path}}">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">Submit</button>
        {% endbuttons %}
    </form>


    <div class="container">
        {% for post in user_object_list %}
            <div class="card">
                <div class="card-header"> {{ post.user }} </div>
                <div class="card-body">
                    <p class="card-text" >{{ post.text }}</p>
                    <a href="#" class="btn " data-emojiable="true">それな</a>
                </div>
            </div>
        {% endfor %}
    </div>
</div>



<script>
    $(function() {
        window.emojiPicker = new EmojiPicker({
            emojiable_selector: '[data-emojiable=true]',
            assetsPath: "/static/tweet/img",
            popupButtonClasses: 'fa fa-smile-o'
        });
        window.emojiPicker.discover();
    });
</script>


<div class="col-sm-4">

    <h3>掲示テキスト</h3>
    {% for post in fix_post_list %}
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">{{ post.title }}</h4>
                <p>{{ post.created_date }}</p>
                <p class="card-text">{{ post.text | linebreaks }}</p>
            </div>
        </div>
    {% endfor %}

    <h2>うみさまのつぶやき</h2>
    {% for post in root_object_list %}
        <div class="card">
            <div class="card-body">
                <h3 class="card-title">{{ post.text }}</h3>
                <a href="#" class="btn btn-primary">それな</a>
            </div>
        </div>
    {% endfor %}
</div>

{% endblock %}

twitter/tweet/templates/tweet/post_list.html
{% extends 'tweet/base.html' %}

{% block content %}
<h1>New post</h1>
<form method="POST" class="post-form" action="/">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="save btn btn-default">Save</button>
</form>

{% for post in posts %}
<div class="post">
    <div class="date">
        {{ post.created_date }}
    </div>
    <h1>{{ post.text}} ~{{post.user}}~</h1>
</div>
{% endfor %}

{% endblock %}